Changes after Roma's comments
uploadcare/uploadcare-wordpress pull request #65
Opened 2020-11-19 14:23 UTC by michaos1

## Description

Updated readmes

2020-11-19 22:36 UTC, rsedykh commented on README.md
> +* Transfer your existing Media Library to your Uploadcare storage with no risk of data loss.
Был специально акцент на том, что это cloud storage. Это конечно очевидно, но..

2020-11-19 22:36 UTC, rsedykh commented on README.md
> +Uploadcare, all-round media storage, management and delivery solution, breaks many of the standard WordPress Media Library limitations. Upload and store files of any size from any device or cloud ser
А это изменение точно нужно в ридми гитхаб репо?

2020-11-19 22:36 UTC, rsedykh commented on README.txt
> +This plugin allows WordPress authors upload images and other files with Uploadcare File Uploader while creating posts and pages. You can upload from local disks, camera, social media, and many other
Какое-то дублирование идет.. Как-то это странно.

2020-11-19 22:36 UTC, rsedykh commented on README.txt
> +* Transfer your existing Media Library to your Uploadcare storage with no risk of data loss.
Аналогичный вопрос.

2020-11-19 22:44 UTC, michaos1 commented on README.md
> +* Transfer your existing Media Library to your Uploadcare storage with no risk of data loss.
да очевидно, по этому убрал, еще не так давно было засилье cloud везде, а сейчас уже почти это не используют. Мы еще говорим cloud для всех подряд сервисов в пункте выше.
кстати, там в тесте были отсылки к local Media Library. я не знаю всех деталей как WP работает, но Library точно может быть на другом хосте. это так, FYI, без предложений что-то менять по тексту.

2020-11-19 22:51 UTC, michaos1 commented on README.md
> +Uploadcare, all-round media storage, management and delivery solution, breaks many of the standard WordPress Media Library limitations. Upload and store files of any size from any device or cloud ser
думаю одинаково сделать и для юзеров и для разрабов. 1 описать UC, все-таки это важнее всего. 2 что плагин делает и как помогает прокачать WP. а дальше там по фичам видно.
Кстати там встроенный респонсив и Lazy loading тоже. Но загружать отовсюду нельзя. Потом, осн часть website performance (без UC) зависит от хоста где WP (я на амазоне заводил и CDN автоматом конечно же подрубился). эти детали тоже нет смысла разжевывать.

2020-11-19 22:51 UTC, michaos1 commented on README.txt
> +This plugin allows WordPress authors upload images and other files with Uploadcare File Uploader while creating posts and pages. You can upload from local disks, camera, social media, and many other
да надо еще поджать

2020-11-19 23:12 UTC, rsedykh commented on README.txt
> +This plugin allows WordPress authors upload images and other files with Uploadcare File Uploader while creating posts and pages. You can upload from local disks, camera, social media, and many other
И там и там в общем оптимизируй этот кусок текста, и всё.

2020-11-23 14:28 UTC, michaos1 commented
хмм, странно, последний пуш как-то не высветился. хотя в Files Changed все ок - посл. версия

2020-11-23 14:29 UTC, michaos1 commented
а так мне кажется нужно мержить @rsedykh

2020-11-23 18:12 UTC, rsedykh requested changes
Написал для readme.md. Для readme.txt — те же самые.

2020-11-23 18:12 UTC, rsedykh commented on README.md
> +This plugin allows WordPress authors upload images with Uploadcare File Uploader while creating posts and pages. You can migrate your current Media Library to your Uploadcare storage, use Adaptive De
Не думаю, что тут стоит использовать проприетарные термины. Я вообще не понимаю, зачем нужен этот абзац.

2020-11-23 18:12 UTC, rsedykh commented on README.md
> +* Upload from your device, social network or cloud: Facebook, Instagram, Dropbox, and others.
```suggestion
* Upload from your device, URL, social network (Facebook, Instagram, VK, Flickr), and cloud (Dropbox, Google Drive, Google Photos, OneDrive, Box, Huddle, Evernote).
```

2020-11-23 18:12 UTC, rsedykh commented on README.md
> +* Uploadcare CDN serves images faster in all parts of the world. Adaptive Delivery analyzes users' context and serves images in a suitable format, resolution, compression, etc.
Мб добавить, что AD делает это для того, чтобы избавить вас от мануальной работы?

2020-11-24 10:22 UTC, michaos1 commented on README.md
> +This plugin allows WordPress authors upload images with Uploadcare File Uploader while creating posts and pages. You can migrate your current Media Library to your Uploadcare storage, use Adaptive De
1 абзац - что такое Uploadcare,
2 абзац что позволяет делать плагин: добавляет Uploading option, миграцию (new) и позволяет пользоваться всем тем из 1го абзаца. Кто уже наш клиент и знает про Adaptive Delivery (new), то здорово! Они теперь могут юзать плагин со своим WP. Если не знает, тоже не беда, тк упоминаем, что это Uploadcare feature.

2020-11-24 10:26 UTC, michaos1 commented on README.md
> +This plugin allows WordPress authors upload images with Uploadcare File Uploader while creating posts and pages. You can migrate your current Media Library to your Uploadcare storage, use Adaptive De
```suggestion
This plugin allows WordPress authors upload images with Uploadcare File Uploader while creating posts and pages. You can migrate your current Media Library to your Uploadcare storage, and use other Uploadcare features.
```

2020-11-24 11:41 UTC, rsedykh approved these changes

2020-11-24 11:41 UTC, merged